### PR TITLE
Python3.6 - Migration

### PR DESCRIPTION
**Pull request by lfdesousa**
Hi,
I have fixed some bugs on the code, too fast on the previous commit and on top of that I have added a CI build using Travis that you can follow it here: 

https://travis-ci.org/lfdesousa/elasticache-auto-discovery/builds

### CODE REVIEW

**Comment by djmitche** [comment]
I like it!  I'm going to squash all those changes together..

**Comment by djmitche** [comment]
I enabled Travis on the repo as well.

**Comment by lfdesousa** [comment]
Great :-) thanks

**Comment by djmitche** [comment]
1.0.0 is released on pypi :)

**Pull request merged**
